# Generated by Django 2.2.12 on 2020-09-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200908_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
